<pre>
<span class="core-_default_ statusbar-_default_" title="statusbar._default_">/usr/local/share/man/man1/mc.1                                           1165/8192+ UTF-8           </span>
<span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">MC</span><span class="core-_default_ viewer-_default_" title="viewer._default_">(1)                                  GNU Midnight Commander                                 </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">MC</span><span class="core-_default_ viewer-_default_" title="viewer._default_">(1) </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_ viewer-viewbold" title="viewer.viewbold">NAME</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       mc - Visual shell for Unix-like systems.                                                     </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_ viewer-viewbold" title="viewer.viewbold">SYNOPSIS</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                            </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewbold" title="viewer.viewbold">mc</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> [-abcCdfhPstuUVx] [-l log] [dir1 [dir2]] [-e [file] ...] [-v file]                        </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_ viewer-viewbold" title="viewer.viewbold">DESCRIPTION</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                         </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       GNU Midnight Commander is a directory browser/file manager for Unix-like operating systems.  </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_ viewer-viewbold" title="viewer.viewbold">OPTIONS</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                             </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">-a,</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--stickchars</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                             </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Disable usage of graphic characters for line drawing.                                 </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">-b,</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--nocolor</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Force black and white display.                                                        </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">-c,</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--color</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                  </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Force color mode, please check the section Colors for more information.               </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">-C</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">arg,</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--colors=arg</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                         </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Specify  a  different color set in the command line.  The format of arg is documented </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              in the Colors section.                                                                </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--configure-options</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                          </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Display configure options.                                                            </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                                    </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">       </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">-d,</span><span class="core-_default_ viewer-_default_" title="viewer._default_"> </span><span class="core-_default_ viewer-_default_ viewer-viewunderline" title="viewer.viewunderline">--nomouse</span><span class="core-_default_ viewer-_default_" title="viewer._default_">                                                                                </span>
<span class="core-_default_ viewer-_default_" title="viewer._default_">              Disable mouse support.                                                                </span>
<span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 1</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Help    </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 2</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">UnWrap  </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 3</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Quit    </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 4</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Hex     </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 5</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Goto    </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 6</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">        </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 7</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Search  </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 8</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Raw     </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey"> 9</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Unform  </span><span class="core-_default_ buttonbar-_default_ buttonbar-hotkey" title="buttonbar.hotkey">10</span><span class="core-_default_ buttonbar-_default_ buttonbar-button" title="buttonbar.button">Quit    </span>
</pre>
