name: Deploy static content to Pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - deploy-skins
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: MidnightCommander/mc
          path: mc

      - run: |
          cp -r src dist

          REV_SE=$(git rev-parse --short HEAD)
          REV_MC=$(cd mc; git rev-parse --short HEAD)

          cp mc/misc/skins/*.ini dist/skins/
          python3 generate-skin-list.py
          mv skins.json dist/

          sed -i 's/REV_SE/$REV_SE/g' dist/index.html
          sed -i 's/REV_MC/$REV_MC/g' dist/index.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - uses: actions/deploy-pages@v4
        id: deployment
